title: haxorhead's blog
description: "/home/haxorhead"
author:
  name: "haxorhead"
  email: "h4xorhead@gmail.com"
  url: "https://sharathunni.github.io/haxorhead-blog/"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "@haxorhead"
year : "2019"
